version: '3'
services:
  video-eureka-server1:
    restart: always
    build: ./cmcc-eureka-server1                # 创建镜像，会自动执行当前目录下eureka文件夹中的Dockerfile文件
    image: "eureka/cmcc-eureka-server1:image-version"   # 镜像名：标签名
    hostname: eureka-server1                    # 注册中心的hostname一定要有，且必须和代码中配置文件里的hostname一致
    networks:
      - finance-net                             # 加入的网络
    ports:
      - "8761:8761"                             # 映射的端口号，和代码中配置文件里的端口号一致
    links:
      - video-eureka-server2
  video-eureka-server2:
    restart: always
    build: ./cmcc-eureka-server2                # 创建镜像，会自动执行当前目录下eureka文件夹中的Dockerfile文件
    image: "eureka/cmcc-eureka-server2:image-version"   # 镜像名：标签名
    hostname: eureka-server2                    # 注册中心的hostname一定要有，且必须和代码中配置文件里的hostname一致
    networks:
      - finance-net                             # 加入的网络
    ports:
      - "8762:8762"                             # 映射的端口号，和代码中配置文件里的端口号一致
    links:
      - video-eureka-server1
  video-boot-admin:
    restart: always
    build: ./cmcc-boot-admin
    image: "admin/cmcc-boot-admin:image-version"
    networks:
      - finance-net
    depends_on:
      - video-eureka-server1                    # 依赖的服务，其启动后才启动当前服务
      - video-eureka-server2
    ports:
      - "8002:8002"
    links:
      - video-eureka-server1
      - video-eureka-server2                    # 要连接服务的名字
  video-zuul:
    restart: always
    build: ./cmcc-zuul
    image: "zuul/cmcc-zuul:image-version"
    networks:
      - finance-net
    depends_on:
      - video-eureka-server1
      - video-eureka-server2
    ports:
      - "8001:8001"
    links:
      - video-eureka-server1
      - video-eureka-server2
  video-zipkin-server:
    restart: always
    build: ./cmcc-zipkin-server
    image: "zipkin/cmcc-zipkin-server:image-version"
    networks:
      - finance-net
    depends_on:
      - video-eureka-server1
      - video-eureka-server2
    ports:
      - "8003:8003"
    links:
      - video-eureka-server1
      - video-eureka-server2
  video-meeting-server:
    restart: always
    build: ./cmcc-meeting-server
    image: "meeting/cmcc-meeting-server:image-version"
    networks:
      - finance-net
    depends_on:
      - video-eureka-server1
      - video-eureka-server2
    ports:
      - "8085:8085"
    links:
      - video-eureka-server1
      - video-eureka-server2
  video-template-server:
    restart: always
    build: ./cmcc-template-server
    image: "template/cmcc-template-server:image-version"
    networks:
      - finance-net
    depends_on:
      - video-eureka-server1
      - video-eureka-server2
    ports:
      - "8086:8086"
    links:
      - video-eureka-server1
      - video-eureka-server2
networks:
  finance-net:
    driver: bridge                      #以桥接模式创建自定义网络，否则会使用默认的网络