apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: video-meeting-server
  name: video-meeting-server
spec:
  ports:
  - name: "8085"
    port: 8085
    targetPort: 8085
  selector:
    io.kompose.service: video-meeting-server
status:
  loadBalancer: {}
