apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: video-template-server
  name: video-template-server
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: video-template-server
    spec:
      containers:
      - image: swr.cn-north-4.myhuaweicloud.com/cmccvideo/template:image-version
        name: video-template-server
        ports:
        - containerPort: 8086
        resources: {}
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
status: {}
